apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-vm
spec:
  generators:
  - pullRequest:
      requeueAfterSeconds: 120
      github:
        owner: automationiberia
        repo: gitops-demo
        labels:
          - preview
 template:
    metadata:
      name: 'bgd-{{branch}}-{{number}}'
    spec:
      source:
        repoURL: 'https://github.com/automationiberia/gitops-demo.git'
        targetRevision: preview-envs
        path: applicationsets/demo-vm/kustomize/base
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'demo-{{branch}}-{{number}}'
...
