apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-ds-rhel9
    spec:
      sourceRef:
        kind: DataSource
        name: rhel9
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm-ds-rhel9
        name: demo-vm-ds-rhel9
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: rhel9
            password: rhel9
            chpasswd: { expire: False }
            runcmd:
              - echo 'Running on $hostname' > /tmp/cloud_name
        name: cloudinitdisk
