apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: demo-vm
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: demo-vm-ds-rhel9
    spec:
      sourceRef:
        kind: DataSource
        name: rhel9
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    spec:
      terminationGracePeriodSeconds: 180
      domain:
        devices:
          rng: {}
        memory:
          guest: 1024M
      volumes:
      - dataVolume:
          name: demo-vm-ds-rhel9
        name: demo-vm-ds-rhel9
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: fedora
            password: fedora
            chpasswd: { expire: False }
            runcmd:
              - echo 'Running on $hostname' > /tmp/cloud_name
              - podman run -itd --name simple-http -p8080:8080 quay.io/automationiberia/ot2024/simple-http:prod
              - podman run -itd --name simple-http -p8081:8081 quay.io/automationiberia/ot2024/2048:prod
        name: cloudinitdisk
